version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: 
      - "5432:5432"
    networks: 
      - "service"
    volumes:
      - ./data:/var/lib/postgresql/
  idp:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
networks:
  service:
